FROM node:20.2.0

COPY . /app
WORKDIR /app

ARG NEXT_PUBLIC_BACKEND_URL
ENV NEXT_PUBLIC_BACKEND_URL=$NEXT_PUBLIC_BACKEND_URL

ARG NEXT_PRIVATE_USERNAME
ENV NEXT_PRIVATE_USERNAME=$NEXT_PRIVATE_USERNAME

ARG NEXT_PRIVATE_PASSWORD
ENV NEXT_PRIVATE_PASSWORD=$NEXT_PRIVATE_PASSWORD

RUN yarn
RUN make build

CMD ["make", "start"]