import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  if (process.env.NEXT_MANUAL_SIG_HANDLE) {
    console.log("here 2");
    process.on("SIGTERM", () => {
      console.log("Received SIGTERM: cleaning up");
      process.exit(0);
    });

    process.on("SIGINT", () => {
      console.log("Received SIGINT: cleaning up");
      process.exit(0);
    });
  }

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
